---
title: 'Week 5: R functions'
author: "Pham Vo"
date: "2/7/2022"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r}

```
# Example input vectors to start with
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)

#Q1. Write a grade() function to determine an overall grade from a vector 

# To find the position of the smallest value (i.e. min) value in our vector 

student1[which.min(student1)]


mean(student1[-which.min(student1)])

#So lets map/change the NA values to zero. Use the "is.na()" function

is.na(student2)

x <- student2
x

x[is.na(x)]b <- 0
x
mean(x)

#Combine our working snippets to find the average for figure 3 

grade <- function(x) {
  x[is.na(x)] <- 0
  mean(x[-which.min(x)])
}

grade(student3)

#Your final function should be adquately explained with code comments and be able to work on an example class gradebook such as this one in CSV format:

url <- "https://tinyurl.com/gradeinput"
gradebook <- read.csv(url, row.names=1)
gradebook

apply(gradebook, 1, grade)

#Q2. Who is the top scoring student overall in the grade book?

result <- apply(gradebook, 1, grade)
sort(result, decreasing = TRUE)

which.max(result)

#Q3. Which homework was toughest on students?

hw.ave <- apply(gradebook, 2, mean, na.rm=TRUE)
which.min(hw.ave)

hw.med <- apply(gradebook, 2, median, na.rm=TRUE)
which.min(hw.med)

#There is a different rest when using mean and median. Good idea to plot the data and see.

boxplot(gradebook)

#Q4. From your analysis of the gradebook, which homework was most predictive of overall score (i.e. highest correlation with average grade score)?


result
gradebook[is.na(gradebook)] <- 0
cor(result, gradebook$hw5, )


apply(gradebook, 2, cor, x=result)

#Q5. Make sure you save your Rmarkdown document and can click the “Knit” button to generate a PDF foramt report without errors. Finally, submit your PDF to gradescope. [1pt]


