CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Leucine-rich      -MAALLRSARWLLRAGAAPRLPLSLRLLPGGPGRLHAASYLPAARAGPVAGGLLSPARLY
Leucine-rich      ------------------------------------------------------------
leucine-rich      -MAALLSWACRL-----RPLCSHLLLRLPRGVAAHRPALRAAGLVGAPGSTHLIYQARLF
leucine-rich      MMAALLGSACRL-----RPLWSRLLR-LPRGVAAHHPSPRAAGLAGAPGSTQLIYHARLF
leucine-rich      ------------------------------------------------------------
                                                                              

Leucine-rich      AIAAKEKDIQEESTFSS--RKISNQFDWALMRLDLSVRRTGRIPKKLLQKVFNDTCRSGG
Leucine-rich      ------------------------------------------------------------
leucine-rich      AIAPHQKGKVQEEPVLSVQNKQAQHFDWALNKLDSSVRRTGRITRTLLLRIFHDMCRTGY
leucine-rich      AIAPHQKGKVQEEPVSGIQNKQAQHFDWALNKLDSSVRRTGRITRTLLQRIFHDMCRTGY
leucine-rich      ------------------------------------------------------------
                                                                              

Leucine-rich      LGGSHALLLLRSCGSLLPELKLEERTEFAHRIWDTLQKLGAVYDVSHYNALLKVYLQNEY
Leucine-rich      ------------------------------------------------------------
leucine-rich      PSSNQALLLLRSCGSLLPEVPLCERTELAHMIWGKLQDLGAVYDASHYNALLKVYLQNEH
leucine-rich      PSSNQALLLLRSCGSLLPEVPLCERTELAHMMWGKLQDLGAVYDASHYNALLKVYLQNEH
leucine-rich      ------------------------------MIWGKLQDLGAVYDASHYNALLKVYLQNEH
                                                                              

Leucine-rich      KFSPTDFLAKMEEANIQPNRVTYQRLIASYCNVGDIEGASKILGFMKTKDLPVTEAVFSA
Leucine-rich      ------------------------------------------------------------
leucine-rich      KFSPTEFLSKMEEANVQPNRVTYQRLIAAYCNEGDIEGASKILGFMKMKELPITEAVFSS
leucine-rich      KFSPTEFLSKMEQANVQPNRVTYQRLIAAYCNEGDIEGASKILGFMKMKELPITEAVFSS
leucine-rich      KFSPTEFLSKMEEANVQPNRVTYQRLIAAYCNEGDIEGASKILGFMKMKELPITEAVFSS
                                                                              

Leucine-rich      LVTGHARAGDMENAENILTVMRDAGIEPGPDTYLALLNAYAEKGDIDHVKQTLEKVEKSE
Leucine-rich      ------------------------------------------------------------
leucine-rich      LVTGHARTGDMENAENIFSVMRDAGIEPGPDTYLALLNAYAEKGDINSVKQILEKIEKME
leucine-rich      LVTGHARAGDMENAENILSVMRDAGIEPGPDTYLALLNAYAEKGDINNIKQILEKVEKME
leucine-rich      LLTGHARTGDMENAENILSVMRDAGIEPGPDTYLALLNAYAEKGDINNVKQILEKVEKME
                                                                              

Leucine-rich      LHLMDRDLLQIIFSFSKAGYPQYVSEILEKVTCERRYIPDAMNLILLLVTEKLEDVALQI
Leucine-rich      ------------------------------------------------------------
leucine-rich      GYLMDRDLLQVIYSLAKAGYPQYVPDILSQMRYERGYIPDAMNLSLNLITQGLEDTAFQV
leucine-rich      GYFMDRDLMQVIFSLAKAGYPQYVQDILSHMRYERGYIPDAMNLSLNLITQGLEDIAFQV
leucine-rich      GYFMDRDLMQVIYSLAKAGYPQYVQDILSQMRYERGYIPDAMNLSLNLITQGLEDTAFQV
                                                                              

Leucine-rich      LLACPVSKEDGPSV----FGSFFLQHCVTMNTPVEKLTDYCKKLKEVQMHSFPLQFTLHC
Leucine-rich      ------------------------------------------------MHS---------
leucine-rich      FKSFPTLPSENHSETSMDYGNFFLQHCVHMDKPLSKLKQFCDELKEANMHSSPLQFTLYC
leucine-rich      FKSFPTLPSENHSESSMDYGNFFLRHCVTTDKPLSKLKQFCDELKEANMHSSPLQFTLYC
leucine-rich      FKSFPTLSSENHSESSMDYGNFFLRHCVTMDKPLSKLKQFCDELKEASIHSSPLQFTLFC
                                                                  :**         

Leucine-rich      ALLANKTDLAKALMKAVKEEGFPIRPHYFWPLLVGRRKEKNVQGIIEILKGMQELGVHPD
Leucine-rich      ------------------------------------------------------------
leucine-rich      ALESKKAALAINLMKTMKEEGLPLRPHYSWPLLVGYQKEKNVQGTIGVLKAMHELGVEPD
leucine-rich      ALESKKAALAINLMKTMKEDGLPLRPHYSWPLLVGYQKEKNVQGTMEVLKALHELGVEPD
leucine-rich      ALESKKAALAINLMKTMKEEGLPLRPHYSWPLLVGYQKEKNVQGTIGVLKAMHELGVEPD
                                                                              

Leucine-rich      QETYTDYVIPCFDSVNSARAILQENGCLSDSDMFSQAGLRSEAANGNLDFVLSFLKSNTL
Leucine-rich      ------------------------------------------------------------
leucine-rich      VETYTNYVLTNFDDIQTFRALLQENGCPFETEGLSVAALRHEAIYGTLENVLSLLSSPSM
leucine-rich      VETYTNYVLTNFDDIQTFRALLQENGCPFETEGLSVAELRHEAIYGTLEKVLSLLSSPSM
leucine-rich      VETYTNYVLTNFDDIQTFRALLQENGCPFETEELSVAELRHEAIYGTLENVLSLLSSPSM
                                                                              

Leucine-rich      P-ISLQSIRSSLLLGFR-RSMNINLWSEITELLYKDGRYCQEPRGPTEAVGYFLYNLIDS
Leucine-rich      --VDLFHFKGCLISGFR-RSKNVDLWSKITELLYKDGRYCQTPPGPSEAVGYFLYNLIDS
leucine-rich      PSVNLSHFKGCLIFGFK-RSNDIDLWSKITELLYKDGRYCQTPPGPAEAVGYFLYNLIDS
leucine-rich      PSVDLFNFKGCLIWALKGKSNDVDLWSKITELLYKDGRYCQTPPGPTEAVGYFLYNLIDS
leucine-rich      PSVDLFHFKGCLIFGFR-RSNDIDLWSKITELLYKDGRYCQTPPGPTEAVGYFLYNLIDS
                    :.*  :...*: .:. .* :::***:************* * **:*************

Leucine-rich      MSDSEVQAKEEHLRQYFHQLEKMNVKIPENIYRGIRNLLESYHVPELIKDAHLLVESKNL
Leucine-rich      MSDSEVQAKEEHLRQYFHQLKKMNIVIPPNIYRGIRNVLDSYHVPELIKDIMLVVDSEKL
leucine-rich      MSDSEVQAKEEHLRQYFHQLKKMNVVIPTNIYRGIRNLLAAYHVPELIKDIILVTDREKL
leucine-rich      MSDSEVQAKEEHLRQYFHQLKKMNVVIPTNIYRGLRNLLDAYHVPELIKDIILLADREKL
leucine-rich      MSDSEVQAKEEHLRQYFHQLKKMNVVIPTNIYRGIRNLLDAYHVPELIKDIILVTDREKL
                  ********************:***: ** *****:**:* :*********  *:.: ::*

Leucine-rich      ---DFQKTVQLTSSELESTLETLKAENQPIRDVLKQLILVLCSEENMQKALELKAKYESD
Leucine-rich      SAADIPKNTELEVLSLEEELEKLKAEKQPIGNVLKQLIVALCAEENMQKALEVKAKYEPD
leucine-rich      SVADIPKNTE--VSALEEELEKLKAEKQPIGNVLKQLIVALCAEENMQKALEVKAKYEPD
leucine-rich      SVADIPKNTELGVSALEEELEKLKAEKQPIGNVLKQLIVALCAEENMQKALEVKAKYESD
leucine-rich      SVADIPKNTELEVSALEEELEKLKAEKQPIGNVLKQLIVALCAEENMQKALEVKAKYEPD
                     *: *..:     **. **.****:*** :******:.**:*********:*****.*

Leucine-rich      MVTGGYAALINLCCRHDKVEDALNLKEEFDRLDSSAVLDTGKYVGLVRVLAKHGKLQDAI
Leucine-rich      MVVGGYAALINLCCRHDNAEDAMNLKEEVYRKDSSVALDTNKYLALVKVLGKHGRLEDAI
leucine-rich      MVVGGYAALINLCCRHDNVEDAMNLKEEVFRKDSSVALDTNKYLALVKVLGKHGRLEDAI
leucine-rich      MVVGGYAALINLCCRHDNVEDAMNLKEEVFRKDSSVALDTNKYLALVKVLGKHGRLEDAI
leucine-rich      MVVGGYAALINLCCRHDNVEDAMNLKEEVFRKDSSVALDTSKYLALVKVLGKHGRLEDAI
                  **.**************:.***:*****. * ***..***.**:.**.**.***.*:***

Leucine-rich      NILKEMKEKDVLIKDTTALSFFHMLNGAALRGEIETVKQLHEAIVTLGLAEPSTNISFPL
Leucine-rich      NILKEMKEKDVPIRDTTVTSFFHILNAAAMQGEVETVNRLHESILTLGLVKPSTNLCSPL
leucine-rich      NILKEIKEKDIPIKDTTVTSFFHILNAAAMRGEVETVNRLHESILTLGLAKPSTNLCTPL
leucine-rich      NILKEMKERDIPIKDTTVTSFFHILNAAAMRGEAETVNRLHESILMLGLAKPSANLCSPL
leucine-rich      NILKEMKEKDIPIKDTTVTSFFHILNAAAMRGEVETVNQLHESILTLGLAKPSANLCSPL
                  *****:**.*: *.***. ****:**.**:.** ***:.***:*: ***.:**:*:. **

Leucine-rich      VTVHLEKGDLSTALEVAIDCYEKYKVLPRIHDVLCKLVEKGETDLIQKAMDFVSQEQGEM
Leucine-rich      ITVHLEKDDVPAALEAAIDCFKKYGNIPRLHDILCRLIEKGNTDLLQKAMDFVSQERGEM
leucine-rich      ITVHLEKDDVPSALEATIDCYKKYGKMPRLHDILCRLIEQGNTELLQKAMDFVSQERGEM
leucine-rich      ITVHLEKDDVPAALEATIDCCKKYGKIPRLHDILCRLIEQGNTDLLQKAMDFVSQERGEM
leucine-rich      ITVHLEKDDVPAALEATIDCCKKYGKIPRLHDVLCRLIEQGNTDLLQKAMDFVSQERGEM
                  :******.*:.:***.:*** :**  :**:**:**.*:*:*:*:*:**********.***

Leucine-rich      VMLYDLFFAFLQTGNYKEAKKIIETPGIRARSARLQWFCDRCVANNQVETLEKLVELTQK
Leucine-rich      TMLYDLFFAFLNTGKYKEAKKIIETPGLRARPGRLQWFAEKCIANNQMDILENMVEMTEK
leucine-rich      MMLYDIFFAFLNTGKYKEAKKIIETPGLRARPGSLQWFAEKCIATNQMETLENMVEMTQK
leucine-rich      TMLYDIFFAFLNTGKYKEAKKIIETPGLRARPGRLQWFAEKCIATNQMETLENMVEMTQK
leucine-rich      TMLYDIFFAFLNTGKYKEAKKIIETPGLRARSGRLQWFAEKCIATNQMETLENMVEMTQK
                   ****:*****:**:************:***.. ****.:.*:*.**:: **::**:*:*

Leucine-rich      LFECDRDQMYYNLLKLYKINGDWQRADAVWNKIQEENVIPREKTLRLLAEILREGNQEVP
Leucine-rich      LFECDRDQMYYYILQLCKISSDWRRADATWTKMQEENVIPRERTLRLLADILKNNGQEVP
leucine-rich      LFECDRDEMYYYLLKLCKISNDWRKAEATWTKMQEENVIPRARTLRLLADTLKNNGQEVP
leucine-rich      LFECDRDQMYYYLLNLCKISNDWQKADATWTKMQEENVIPRERTLRLLADTLKNNGQEVP
leucine-rich      LFECDRDQMYYYLLKLCKISNDWRKADATWTKMQEENVIPRETTLRLLADTLKNNGQEVP
                  *******:*** :*:* **..**..*:*.*.*:********  ******: *.:..****

Leucine-rich      FDVPELWYEDEKHSLNSSSASTTEPDFQKDILIACRLNQKKGAYDIFLNAKEQNIVFNAE
Leucine-rich      FDVPEIWYED-----CVESAPVSENNPEKKILILCKKGNIQEAYNILLEEQKKDIMFPSF
leucine-rich      FDVPEIWYED-----HVESASVLENNPEKKVLMLCKKGSVQEAYNILLEAQKKDIMFPAS
leucine-rich      FDVPEIWYED-----RVESAPVSENNPEKKVLMLCKKGSVQEAYNILLEAQKKDIMFPPS
leucine-rich      FDVPEIWYED-----HVVSAPVSENNPEKKVLMLCKKGSVQEAYNILLEAQKKDIMFPPS
                  *****:****        **.. * : :*.:*: *. .. : **:*:*: ::::*:* . 

Leucine-rich      TYSNLIKLLMSEDYFTQAMEVKAFAETHIKGFTLNDAANSRLIITQVRRDYLKEAVTTLK
Leucine-rich      TYSILIKALLAEGCLEKAINVKNIAETHIKGFTLNDAASSLLIITQVRRDYLKDAISTLK
leucine-rich      AYSTLIKALLAEGCLEEALKVKNIAETHIKGFTLNDAASSLLIITQVRRDYLKDAISTLK
leucine-rich      AYSTLIKALLAEGCLEEAIKVKNIAETHIKGFTLNDAASSLLIITQVRRDYLKDAVSTLK
leucine-rich      VYSTLIKALLAEGCLEEAIKVKNIAETHIKGFTLNDAASSLLIITQVRRDYLKDAMSTLK
                  .** *** *::*. : :*::** :**************.* ************:*::***

Leucine-rich      TVLDQQQTPSRLAVTRVIQALAMKGDVENIEVVQKMLNGLEDSIGLSKMVFINNIALAQI
Leucine-rich      AVLENDMVPTRLAVTRLIQALAMKGDVESVRTVEKMVENLAVSIGLSRMLFVNNTVLAHI
leucine-rich      KVLESDMVPMSLAVIRLIQALAMKGDLESICTVEKMVENLATSIGLSRMLFVNNTVLAHI
leucine-rich      TVLESDMVPIPLAVTRLVQALAMKGDLESICTVEKMVENLAASIGLSRMLFVNNTVWAHI
leucine-rich      TVLESDMVPMPLAVTRLIQALAMKGDLESICTVEKMVENLAASIGLSRMLFVNNTVLAHI
                   **:.: .*  *** *::********:*.: .*:**::.*  *****.*:*:** . *:*

Leucine-rich      KNNNIDAAIENIENMLTSENKVIEPQYFGLAYLFRKVIEEQLEPAVEKISIMAERLANQF
Leucine-rich      KNNNLDTAVEYIESLIISGMQNPDSPITSISYVFRKVIEEKLESALEKLSAMAERLVNQF
leucine-rich      KK----------------------------------------------------------
leucine-rich      KNNNLDMAVEYIEPLFISGMQNPDSPITSMSYVFRKVIEERLEPALEKLSAMAERLVNQF
leucine-rich      KNNNLDMAVEYIEPLFISGMQNPDSPITSMSYVFRKVIEERLEPALEKLSAMAERLVNQF
                  *:                                                          

Leucine-rich      AIYKPVTDFFLQLVDAGKVDDARALLQRCGAIAEQTPILLLFLLRNSRKQGKASTVKSVL
Leucine-rich      GIYKPATDLFLQYVSEGRIDDARLLLQRCGGIAEQKKIMMAFIAKSSQKPGQGQKIKMLL
leucine-rich      ------------------------------------------------------------
leucine-rich      GVYKPATDLFLQYVDAGRVDDARFLLQRCGGIAEQKGTLMAFIAKSSQKPGQGQKIKTLL
leucine-rich      GVYKPATDLFLQYVDAGRVDDARFLLQRCGGIAEQKRILMAFIAKSSQKPGQGQKIKTLL
                                                                              

Leucine-rich      ELIPELNEKEEAYNSLMKSYVSEKDVTSAKALYEHLTAKNTKLDDLFLKRYASLLKYAGE
Leucine-rich      DLVPDFPEMEVVYSYLLKCHVLDNDIVSAKTLFEKAKAENIRTDEIFLKRLAFLLKSAGE
leucine-rich      ------------------------------------------------------------
leucine-rich      DLVPDFPEKEIVYSYLLKCHVLDNDVVSAKALFENMKAKNIHTDEIFLKRLAILLKNAGE
leucine-rich      DLVPDFPDMEIVYSYLLKCHALDNDVVSAKILFEKMKAENIHTDEIFLKRLAILLKNAGE
                                                                              

Leucine-rich      PVPFIEPPESFEFYAQQLRKLRENSS----
Leucine-rich      PVPFTEPPESFHFYVNKLRKERQELSSHDV
leucine-rich      ------------------------------
leucine-rich      PVPFTEPPESFHFYANKLRQERQETSSHDV
leucine-rich      PVPFTEPPESFHFYGKKLRQERQEISSHDV
                                                
