CLUSTAL multiple sequence alignment by MUSCLE (3.8)


NP_080290.3         MAQSRVTDFYACRRPG--LTTPRAKSICLTPSPG--GLVAPAFTRSSSRKRARPPAEPGS
NP_001099662.1      MAQSRVTDFYACRRPG--LAIPRAKSTCLTPSPG--GLVAPEFTRSSSRKRVRPHAEPGS
XP_024089744.1      MEQRRVTDFFARRRPG--PRIAPPKPACRTPSPARPALRSPDSATSGSRKRTRPPADPGR
Ovis                ------------------------------------------------------------
XP_017917346.1      MAQRRLTDFFARRRPGVSTTLPRAKPAWRTPSPAKSAACAAAPGPGSSRKRARPPAEPTR
XP_005218826.1      MAQRRLTDFFARRRPGGSATLPRAKPAWRTPSPAKSAPCAAAPGPGSSRKRTRPPAEPTR
XP_010842264.1      MAQRRLTDFFARRRPGGSATLPRAKPAWRTPSPAKSAPCAAAPGPGSSRKRTRPPAEPTR
                                                                                

NP_080290.3         DQPAPLARRRLRLPGLDSCPSSLPEPSSPAEPSPPADPSPPADPGSPVCPSPVKRTKSTT
NP_001099662.1      DQPAPPARRRLRLPGLDSCPSFPADPSSPADPSSPADPSSSVCP-SPVCPSPVKRTKSTT
XP_024089744.1      DQASPLARRRLRLSA-----DEVSSPSTPEAPDSPKTPD------IPACPSLGQKIKKST
Ovis                ------------------------------------------------------------
XP_017917346.1      DERVPPARKRLRLPA-----DAVSGPSSPPAPVSPEHP-------SPQSKETKKAARSAG
XP_005218826.1      DERVPPARKRLKLSA-----DAVSGPSSPAARGSPEHP-------SPQSKETKKAARSAG
XP_010842264.1      DERVPPARKRLKLSA-----DAVSGPSSPAAPGSPEHP-------SPQSKETKKAARSAG
                                                                                

NP_080290.3         VYVG--QQPGKIPSEDSVSELQSCLRRARKLGAQARALRARVQENAVEPSTPDAKVPTEQ
NP_001099662.1      VSRG--PQQSKVPSQDSISELQSCLRQARKLGAQARALRARVQENVVEPSTPDTKEPTEQ
XP_024089744.1      PAAGQPPHPTSPQDQDTISELASCLQRARELGARVRALKASAQ-DAEESCTPEAEGPPEE
Ovis                ------------------------------------------------------------
XP_017917346.1      GPPCLAAQENKVPSKVTLSELKSCLQRAQELGARVQELKASAQKDAGEPSAPEDEGRLEG
XP_005218826.1      GRPCLAAQENKVPSKVTLSELKSCLQRAQELGARFQELKASAQKDAGEPSAPEDEGRLEE
XP_010842264.1      GRPCLAAQENKVPSKVTLSELKSCLQRAQELGARFQELKASAQKDAGEPSAPEDEGRLEE
                                                                                

NP_080290.3         PCVEKAPAYQRFHALAQPGLPGLVLPYKYQVLVEMFRSMDTIVSMLHNRSETVTFAKVKQ
NP_001099662.1      PCVDKAPAYQRFHALAQPGLPGLVLPYKYQVLAEMFRSMDTIVSMLHNRSETVTFAKVKQ
XP_024089744.1      QWGEKAPAYQRFHALAQPGLPGLMLPYKYQVLAEMFRSMDTIVGMLHNRSETPTFAKVQR
Ovis                ------------------------------------------------------------
XP_017917346.1      PCGEQMPAYQRFHALAQPGPPGLVLPYKYQVLAEMFRSMDTIVGMLYNRSETITFAKVKQ
XP_005218826.1      PCGEQMPAYQRFHALAQPGLPGLVLPYKYQVLSEMFRSMDTIVGMLYNRSETVTFAKVKQ
XP_010842264.1      PCGEQMPAYQRFHALAQPGLPGLVLPYKYQVLAEMFRSMDTIVGMLYNRSETVTFAKVKQ
                                                                                

NP_080290.3         GVQEMMRKRFEERNVGQIKTVYPTSYRFRQECNVPTFKDSIKRSDYQLTIEPLLGQEAGG
NP_001099662.1      GVQEMIRKRFEERNMGQIKTVYPESYSFRQECNVPTFKDSIKRSDYQLTIEPLLGQEAGG
XP_024089744.1      GVQDMMRRRFEERNVGQIKTVYPASYRFRQERSVPTFKDGVKKSDYQLTIEPLLEQEADG
Ovis                -VQDMMRKRFEERNVGQIRTVYPACYRFRQERNIPTFKDGIKRSDYQLTIEPVLDQEAGS
XP_017917346.1      GVQDMMRKRFEERNVGQIKTVYPGSYHFRQERFVPTFKDGIKRSDYQLTIEPLLDQQAGS
XP_005218826.1      GVQDMMRKRFEERNVGQIKTVYPGSYHFRQERFVPTFKDGIKRSDYQLTIEPLLDQQAGS
XP_010842264.1      GVQDMMRKRFEERNVGQIKTVYPGSYHFRQERFVPTFKDGIKRSDYQLTIEPLLDQQAGS
                     **:*:*.******:***.**** .* ****  :*****.:*.*********:* *:*..

NP_080290.3         AT-QLTATCLLQRRQVFRQNLVERVKEQHKVFLASLNPPMAVPDDQLTRWHPRFNVDEVP
NP_001099662.1      AT-QLTATGLLQRRQVFRQNLVERVKEHHKVFLASLNPPMTVPEDQLTRWHPRFNVDEVP
XP_024089744.1      AAPQLTASRLLQRRQIFSQKLVEHVKEHHKAFLASLSPPMVVPEDQLTRWHPRFNVDEVP
Ovis                AAPQLTASHLLQRRQVFSQNLVERVREHHRAFLASLNPPMVVPEERLTRWHPRFNVDEVP
XP_017917346.1      AAPQLTASRLLQRRQVFSQNLLARVREHHRAFLASLNPPMEVPEDQLTRWHPRFNVDGVP
XP_005218826.1      AAPQLTASRLLQRRQVFSQNLVARVREHHRAFLASLNPPMEVPEDQLTRWHPRFNVDGVP
XP_010842264.1      AAPQLTASRLLQRRQVFSQNLVARVREHHRAFLASLNPPMEVPEDQLTRWHPRFNVDGVP
                    *: ****: ******:* *:*: .*.*:*..*****.*** **::.*********** **

NP_080290.3         DIEPAELPQPPVTEKLTTAQEVLARARSLMTPKMEKALSNLALRSAEPGSPGTSTPPLPA
NP_001099662.1      DIEPAELPQPPVTEKLTTAQEVLARARNLMTPKMEKALSNLALRSAEPGSPGTSSPALPA
XP_024089744.1      DIEPAALPQPPAMEKLTTAQEVLARARNLISPRMEKALSQLALRSAVPSSPGSPRPALPA
Ovis                DIEPAELPRPPATEKVATAQEVLARARGLMSPRMEKALSDLALR----------------
XP_017917346.1      DIEPAELPQPPAVEKLTTAQEVLARARSLMSPRMEKALSDLAQRTAEPSSPRSPSLAQPA
XP_005218826.1      DIEPAELPQPPAVEKLTTAQEVLARARSLMSPRMEKALSDLAQRTAEPSSPRSPSLAQPA
XP_010842264.1      DIEPAELPQPPAVEKLTTAQEVLARARSLMSPRMEKALSDLAQRTAEPSSPRSPSLAQPA
                    ***** **.**. **::**********.*::*.******:** *                

NP_080290.3         TPPATPPAASPSALKGVSQALLERIRAKEVQKQLARMTRCPEQELRLQRLERLPELARVL
NP_001099662.1      TPPATPPAASPSALKGVSQALLERIRAKEVQKQLARMTRCPEKELRLQRLERLPELARVL
XP_024089744.1      TPPATPPAASPSALKGVSQDLLERIRAKEAQKQLAQMTRCPEQEQRLQRLERLPELARVL
Ovis                ------------------------------------------------------------
XP_017917346.1      TPPAAP----PSALKGVSQALLERIRAKEAQKQLAQMTRRPEQEQRLQRLERLPELARVL
XP_005218826.1      TPPATPPAAPPSALKGVSQALLERIRAKEAQKQLAQMTRRPEQEQRLQRLERLPELARVL
XP_010842264.1      TPPATPPAAPPSALKGVSQALLERIRAKEAQKQLAQMTRRPEQEQRLQRLERLPELARVL
                                                                                

NP_080290.3         RNVFVSERKPALTMEVVCARMVDSCQTALSPGEMEKHLVLLAELLPDWLSLHRIRTDTYV
NP_001099662.1      RGVFVSERKPALTMEVVCARMVDSSRAALSPGEMEKHLLLLAELLPDWLSLHRVRTDTYV
XP_024089744.1      RSVFVSERKPALSMEVACARMVGSCRTVMSPGEMEKHLLLLSELLPDWLSLHRIRTDTYV
Ovis                ------------------------------------------------------------
XP_017917346.1      RGVFVSERKPALTMEVACARMVGSYRAAMSPGEMEKHLQLLSELLPDWLSLHRIRTDTYV
XP_005218826.1      RGVFVSERKPALTMEVACARMVGSYRAAMSPGEMEKHLQLLSELLPDWLSLHRIRTDTYV
XP_010842264.1      RGVFVSERKPALTMEVACARMVGSYRAAMSPGEMEKHLQLLSELLPDWLSLHRIRTDTYV
                                                                                

NP_080290.3         KLDKAVDLAGLTARLAHHVHA-EGL
NP_001099662.1      KLDKAADLAGLTAKLARQVHA-EGL
XP_024089744.1      KLDKAADLANITARLAHQAHAEEGL
Ovis                -------------------------
XP_017917346.1      KLDKAADLAGVMEQLARLARAEETL
XP_005218826.1      KLDKAADLAGVMEQLAHLARAEETL
XP_010842264.1      KLDKAADLADVMEQLARLARAEETL
                                             
